# Generated by Django 2.0.4 on 2018-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20180422_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Query Title'),
        ),
    ]
