# Generated by Django 2.0.3 on 2018-03-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_auto_20180314_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
