# Generated by Django 2.0.3 on 2018-03-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_auto_20180314_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posted',
        ),
    ]
