# Generated by Django 2.0.3 on 2018-03-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_auto_20180314_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted',
            new_name='post',
        ),
    ]
