# Generated by Django 2.0.3 on 2018-03-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0005_auto_20180314_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_name',
        ),
    ]
