# Generated by Django 2.0.3 on 2018-03-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0006_auto_20180314_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_name',
            new_name='post',
        ),
    ]
