# Generated by Django 2.0.3 on 2018-03-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0008_auto_20180314_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
