# Generated by Django 2.0.3 on 2018-04-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0016_auto_20180316_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
