# Generated by Django 2.0.4 on 2018-04-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0017_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
