# Generated by Django 2.0.4 on 2018-04-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0018_auto_20180418_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
