# Generated by Django 2.0.4 on 2018-04-22 10:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0019_auto_20180418_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=ckeditor.fields.RichTextField(verbose_name='Leave a Comment :'),
        ),
    ]
